//var dotenv = require('dotenv');
//dotenv.load();
require('dotenv').config();
var fs = require('fs');
var cloudinary = require('cloudinary').v2;

var uploads = {};
console.log("cloud name: "+process.env.cloud_name);


// set your env variable CLOUDINARY_URL or set the following configuration
cloudinary.config({
  cloud_name: process.env.cloud_name,
  api_key: process.env.api_key,
  api_secret: process.env.api_secret
});

var video = process.argv[2];
var id = "";
if (process.argv[3] != null ){
	id = process.argv[3];
 }
console.log( "** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");

// File upload
cloudinary.uploader.upload(process.argv[2], { resource_type: "video", public_id: id,  

//add any language you'd like the captions translated to:
//list of available languages: https://api-portal.videoindexer.ai/docs/services/operations/operations/Get-Video-Index?&pattern=index
    raw_convert: "azure_video_indexer:vtt:en-US:fr-FR:es-ES:zh-Hant:th-TH:he-IL:sw-KE" },function(err,result){
  console.log(result);
  console.log("** File Uploaded!");
  if (err){ console.warn(err);}
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");

});


